// Temporary hardcoded investment fund data for testing - Updated
export const tempFundsData = [
  {
    id: "DC60_1",
    name: "Quỹ Phát Triển Trạm Sạc VinFast (DC 60kW)",
    code: "DC60_1",
    category: "Hạ tầng sạc",
    duration: 30,
    minInvestment: "50 triệu VND",
    maxInvestment: "500 triệu VND",
    projectScale: "5 tỷ VND",
    dailyReturn: 0.002,
    progress: 30,
    image: "/assets/quy-phat-trien-tram-sac-vinfast-dc-60kw.jpg",
    description: "Quỹ đầu tư phát triển hệ thống trạm sạc DC 60kW",
    features: ["ROI 0.2%/ngày", "Thời gian 30 ngày", "Đầu tư tối thiểu 50 triệu"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "TICH",
    name: "Quỹ mở thẻ tích lũy VinGroup",
    code: "TICH",
    category: "Tích lũy",
    duration: 45,
    minInvestment: "150 triệu VND",
    maxInvestment: "1.5 tỷ VND",
    projectScale: "7.5 tỷ VND",
    dailyReturn: 0.0025,
    progress: 90,
    image: "/assets/quy-mo-the-tich-luy-vingroup.jpg",
    description: "Quỹ mở thẻ tích lũy VinGroup với lợi nhuận ổn định",
    features: ["ROI 0.25%/ngày", "Thời gian 45 ngày", "Đầu tư tối thiểu 150 triệu"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "THUONG",
    name: "Quỹ Phát Triển Trạm Sạc VinFast (Gói THƯỜNG)",
    code: "THUONG",
    category: "Gói Thường",
    duration: 45,
    minInvestment: "300 triệu VND",
    maxInvestment: "3 tỷ VND",
    projectScale: "10 tỷ VND",
    dailyReturn: 0.003,
    progress: 120,
    image: "/assets/quy-phat-trien-tram-sac-vinfast-goi-thuong.jpg",
    description: "Gói đầu tư thường cho các nhà đầu tư cá nhân",
    features: ["ROI 0.3%/ngày", "Thời gian 45 ngày", "Đầu tư tối thiểu 300 triệu"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "VIP",
    name: "Quỹ Phát Triển Trạm Sạc VinFast (Gói VIP)",
    code: "VIP",
    category: "Gói VIP",
    duration: 60,
    minInvestment: "500 triệu VND",
    maxInvestment: "5 tỷ VND",
    projectScale: "15 tỷ VND",
    dailyReturn: 0.0035,
    progress: 150,
    image: "/assets/quy-phat-trien-tram-sac-vinfast-goi-vip.jpg",
    description: "Gói đầu tư VIP cao cấp với dịch vụ độc quyền",
    features: ["ROI 0.35%/ngày", "Thời gian 60 ngày", "Đầu tư tối thiểu 500 triệu"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "DC60",
    name: "Quỹ Phát Triển Trạm Sạc VinFast (DC 60kW)",
    code: "DC60",
    category: "Hạ tầng sạc",
    duration: 60,
    minInvestment: "800 triệu VND",
    maxInvestment: "8 tỷ VND",
    projectScale: "20 tỷ VND",
    dailyReturn: 0.004,
    progress: 200,
    image: "/assets/quy-phat-trien-tram-sac-vinfast-dc-60kw.jpg",
    description: "Quỹ đầu tư phát triển trạm sạc DC 60kW cho khu vực thương mại",
    features: ["ROI 0.4%/ngày", "Thời gian 60 ngày", "Đầu tư tối thiểu 800 triệu"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "DC80",
    name: "Quỹ Phát Triển Trạm Sạc VinFast (DC 80kW)",
    code: "DC80",
    category: "Hạ tầng sạc",
    duration: 90,
    minInvestment: "1 tỷ VND",
    maxInvestment: "10 tỷ VND",
    projectScale: "50 tỷ VND",
    dailyReturn: 0.005,
    progress: 250,
    image: "/assets/quy-phat-trien-tram-sac-vinfast-dc-80kw.jpg",
    description: "Quỹ phát triển hệ thống trạm sạc DC 80kW tại trung tâm thương mại",
    features: ["ROI 0.5%/ngày", "Thời gian 90 ngày", "Đầu tư tối thiểu 1 tỷ"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "DC120",
    name: "Quỹ Phát Triển Trạm Sạc VinFast (DC 120kW)",
    code: "DC120",
    category: "Hạ tầng sạc",
    duration: 90,
    minInvestment: "3 tỷ VND",
    maxInvestment: "30 tỷ VND", 
    projectScale: "100 tỷ VND",
    dailyReturn: 0.006,
    progress: 300,
    image: "/assets/quy-phat-trien-tram-sac-vinfast-dc-120kw.jpg",
    description: "Quỹ đầu tư trạm sạc DC 120kW - Quỹ đầu tư ngắn hạn với bảo mật 100%. Thưởng gói nâng cấp: 246.000.000 VND",
    features: ["ROI 0.6%/ngày", "Thời gian 90 ngày", "Đầu tư tối thiểu 3 tỷ", "Bảo mật 100%", "Không rủi ro"],
    dividend: "0 VND",
    investmentCycle: "90 Ngày", 
    profitMethod: "Quỹ đầu tư ngắn hạn",
    minInvestmentAmount: "3,000,000,000 VND",
    riskFree: "100%",
    projectDetails: {
      projectName: "Quỹ Phát Triển Trạm Sạc VinFast (DC 120kW)",
      projectAmount: "100,000,000,000 VND",
      profitRate: "Tỷ lệ 0.6% thu nhập (vốn và lãi)",
      investmentAmount: "Đầu tư thấp nhất 3,000,000,000 VND (Giới hạn mua 9999 phần)",
      projectDuration: "90 Ngày",
      profitCalculation: "Lãi cộng theo tỉ lệ ngày",
      paymentMethod: "Quỹ đầu tư ngắn hạn",
      settlementTime: "Ngày thứ 31",
      investmentNumber: "VIC",
      security: "100%",
      projectSummary: "Thưởng gói nâng cấp gói: 246.000.000 VND"
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "DC150",
    name: "Quỹ Phát Triển Trạm Sạc VinFast (DC 150kW)",
    code: "DC150",
    category: "Hạ tầng sạc",
    duration: 100,
    minInvestment: "7 tỷ VND",
    maxInvestment: "70 tỷ VND",
    projectScale: "200 tỷ VND",
    dailyReturn: 0.007,
    progress: 365,
    image: "/assets/quy-phat-trien-tram-sac-vinfast-dc-150kw.jpg",
    description: "Quỹ phát triển trạm sạc DC 150kW cao cấp tại sân bay và resort",
    features: ["ROI 0.7%/ngày", "Thời gian 100 ngày", "Đầu tư tối thiểu 7 tỷ"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "3D300",
    name: "Quỹ Phát Triển Trạm Sạc VinFast (3D 300kW)",
    code: "3D300",
    category: "Công nghệ 3D",
    duration: 180,
    minInvestment: "16 tỷ VND",
    maxInvestment: "160 tỷ VND",
    projectScale: "300 tỷ VND",
    dailyReturn: 0.008,
    progress: 400,
    image: "/assets/quy-phat-trien-tram-sac-vinfast-3d-300kw.jpg",
    description: "Quỹ đầu tư công nghệ trạm sạc 3D 300kW thế hệ mới với AI",
    features: ["ROI 0.8%/ngày", "Thời gian 180 ngày", "Đầu tư tối thiểu 16 tỷ"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "VIC01",
    name: "Quỹ Phát Triển Trạm Sạc VinFast (VIC01)",
    code: "VIC01",
    category: "VIC Series",
    duration: 180,
    minInvestment: "25 tỷ VND",
    maxInvestment: "250 tỷ VND",
    projectScale: "500 tỷ VND",
    dailyReturn: 0.01,
    progress: 450,
    image: "/assets/quy-phat-trien-tram-sac-vinfast-vic01.jpg",
    description: "Quỹ đầu tư phát triển hệ thống trạm sạc VinFast VIC01 trên toàn quốc",
    features: ["ROI 1%/ngày", "Thời gian 180 ngày", "Đầu tư tối thiểu 25 tỷ"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "VIC03",
    name: "Quỹ Phát Triển Trạm Sạc VinFast (VIC03)",
    code: "VIC03",
    category: "VIC Series",
    duration: 300,
    minInvestment: "40 tỷ VND",
    maxInvestment: "400 tỷ VND",
    projectScale: "1,000 tỷ VND",
    dailyReturn: 0.012,
    progress: 720,
    image: "/assets/quy-phat-trien-tram-sac-vinfast-vic03.jpg",
    description: "Quỹ đầu tư phát triển trạm sạc VIC03 cho các khu vực thương mại",
    features: ["ROI 1.2%/ngày", "Thời gian 300 ngày", "Đầu tư tối thiểu 40 tỷ"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "VIC07",
    name: "Quỹ Phát Triển Trạm Sạc VinFast (VIC07)",
    code: "VIC07",
    category: "VIC Series",
    duration: 365,
    minInvestment: "60 tỷ VND",
    maxInvestment: "600 tỷ VND",
    projectScale: "2,000 tỷ VND",
    dailyReturn: 0.015,
    progress: 1050,
    image: "/assets/quy-phat-trien-tram-sac-vinfast-vic07.jpg",
    description: "Quỹ phát triển hệ thống trạm sạc VIC07 tại các trung tâm thương mại",
    features: ["ROI 1.5%/ngày", "Thời gian 365 ngày", "Đầu tư tối thiểu 60 tỷ"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "VIC16",
    name: "Quỹ Phát Triển Trạm Sạc VinFast (VIC16)",
    code: "VIC16",
    category: "VIC Series",
    duration: 365,
    minInvestment: "90 tỷ VND",
    maxInvestment: "900 tỷ VND",
    projectScale: "10,000 tỷ VND",
    dailyReturn: 0.018,
    progress: 1400,
    image: "/assets/quy-phat-trien-tram-sac-vinfast-vic16.jpg",
    description: "Quỹ VIC16 phát triển mạng lưới trạm sạc cao cấp tại các thành phố lớn",
    features: ["ROI 1.8%/ngày", "Thời gian 365 ngày", "Đầu tư tối thiểu 90 tỷ"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "VIC25",
    name: "Quỹ Phát Triển Trạm Sạc VinFast (VIC25)",
    code: "VIC25",
    category: "VIC Series",
    duration: 365,
    minInvestment: "150 tỷ VND",
    maxInvestment: "1,500 tỷ VND",
    projectScale: "50,000 tỷ VND",
    dailyReturn: 0.022,
    progress: 1500,
    image: "/assets/quy-phat-trien-tram-sac-vinfast-vic25.jpg",
    description: "Quỹ VIC25 cao cấp nhất phát triển hệ thống trạm sạc thông minh toàn quốc",
    features: ["ROI 2.2%/ngày", "Thời gian 365 ngày", "Đầu tư tối thiểu 150 tỷ"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];
